### ISSUE TITLE
\noexpand in \lsCollectionPaperFooterTitle

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#100]
If `\noexpand\textit{...}` is used _at the beginning_ of `\renewcommand{\lsCollectionPaperFooterTitle}{...}`, then the title in the footer comes out in ALLCAPS, although it is printed correcly in `collection_tmp.bib`. Extra grouping or `\itshape` may prevent this issue.

Example:
`\renewcommand{\lsCollectionPaperFooterTitle}{\noexpand\textit{New discovery} in xyz}`
results in _NEW DISCOVERY_ IN XYZ, but
`\renewcommand{\lsCollectionPaperFooterTitle}{A \noexpand\textit{New discovery} in xyz}`
results in A _New discovery_ in xyz

**Comment by Glottotopia** [comment]
Maybe @timmli has more expertise with expansion and bibliography intricacies than me ...

**Comment by kopeckyf** [comment]
Solved in 62adf230e1c18d65370a055fdc9dc8f63e61c610, where manual setting of `\lsCollectionPaperFooterTitle` is no longer necessary.
