### ISSUE TITLE
Unite "cite" and "cite this volume" commands

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#104]
Currently, we have the usual `\cite` commands, but also additional `\citetv` commands that output "[this volume]". It would be desirable to have only one type of commands that automatically detects whether the given cite key refers to a chapter in the volume or a regular bib resource. Since all items cited in this volume are prefixed with `chapters/` or suffixed with `.tex`, an implementation in `langsci-unified.cbx` should be pretty straight-forward.

**Comment by stefan11** [comment]
I use these commands:

```latex
\newcommand{\crossrefchaptert}[2][]{\citet*[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume} 
\newcommand{\crossrefchapterp}[2][]{(\citealp*[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume)}
\newcommand{\crossrefchapteralt}[2][]{\citealt*[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume}
\newcommand{\crossrefchapteralp}[2][]{\citealp*[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume}
```
The chapters have to have a label corresponding to their file name, e.g. chap-order. The nice effect of this is that the chapter are cited and crossreferenced.

It is called:
```latex
\crossrefchaptert{order}
```

**Comment by kopeckyf** [comment]
Mh, the idea behind this enhancement is to use `\cite{chapters/mueller}` and so consolidate the citation commands. The commands you use are of course fine, but they are hard to remember for the authors and with the extra Chapter reference, take up a lot of space.

**Comment by stefan11** [comment]
You are right: they are hard to remember. They could be renamed. Taking a lot of space is not an issue, I think. It is all digital. The cross reference is worth it.

**Comment by kopeckyf** [comment]
Note to self: we will also need a “this volume” `bibstring`. Let's do this with `\DeclareBibliographyStrings`:

```latex
\DeclareBibliographyStrings
  {
    thisvolume = {<locale for this volume>}
  }
```

**Comment by kopeckyf** [comment]
The “cite this volume” citation commands have now been integrated into the usual citation commands. This works using the new macro `cite:thisvolume`:

```latex
\newbibmacro*{cite:thisvolume}{%
  \ifkeyword{LSPWithinVolume}
    {\addspace\printtext[bibhyperref]{[this volume]}}
    {}%
}
```

This macro recognises any entry that has
```
keywords={LSPWithinVolume}
```
and appends a “this volume” to the citation string. 

**Note** that older versions of `langscibook` used a different `keyword` for chapters of the same volume. They used `withinvolume` instead. As of https://github.com/langsci/langscibook/commit/d6c4c84e671ff31b089fea7e3ba1b1ba5f1f7827, this keyword was changed to `LSPWithinVolume`, because this is more safe from arbitrary user input (a user might themselves use the keyword `withinvolume` as a generic English expression, but if they use `LSPWithinVolume` they're just asking for trouble, and we may reasonably ask them to change their keywords).

**Comment by kopeckyf** [comment]
In effect, this means that all of the following work and append the “this volume” string at the appropriate place:

```latex
% blank
\cite{chapters/02, OtherCitation}
\citealt{chapters/02, OtherCitation}
\citeyear[1]{chapters/02}
% etc etc etc.

% parenthetical
\parencite{chapters/02, OtherCitation}
\citep{chapters/02, OtherCitation}
\Parencite{...}

% narrative
\textcite{chapters/02, OtherCitation}
\Textcite{chapters/02, OtherCitation}
\citet{chapters/02}
% etc etc etc.

% possessive citation
\posscitet[123]{chapters/02}
\posscitealt[123]{chapters/02}
% note that \citegen does **not** work b/c its non-standard right now

% multi-cite work as well
\textcites[123]{chapters/02}[456]{chapters/03}[789]{OtherCitation}
% also \parencites etc etc.
```

**Comment by kopeckyf** [comment]
@stefan11, in order to use these new features with your commands, you will have to slightly adjust them:

(Note that `\citealp` and `\citealt` are exactly the same in `langsci-unified`, because `langsci-unified` does **not** have a name-year delimiter (as opposed to APA, where  `\citealp` and `\citealt` are different). It is thus not necessary to have both `\crossrefchapteralp` and `\crossrefchapteralt`.

```latex
\newcommand{\crossrefchaptert}[2][]{\citeauthor*{chapters/#2} (\citedate[#1]{chapters/#2}), Chapter~\ref{chap-#2} of this volume} 
\newcommand{\crossrefchapterp}[2][]{(\citeauthor*{chapters/#2} \citedate[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume)}
\newcommand{\crossrefchapteralt}[2][]{\citeauthor*{chapters/#2} \citedate[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume}
\newcommand{\crossrefchapteralp}[2][]{\citeauthor*{chapters/#2} \citedate[#1]{chapters/#2}, Chapter~\ref{chap-#2} of this volume}
```

Also note that printing the full author list with `\citeauthor*` is non-standard in the Unified Style Sheet, where _et al._ should normally be used.

Also note that `\citedate` is not the same  as `\citeyear`.
