### ISSUE TITLE
Different spacing \begin{exe} and \ea

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#105]
The spacing between examples differs between usages of the environment and short-cuts, i.e.

```
\begin{exe}
\ex ...
\ex ...
\end{exe}
```

has a **visibly tighter** spacing than
```
\ea
...
\z
\ea
...
\z
```

However, one can use
```
\ea
....
\ex
....
\z
```

to achieve the spacing from the env usage.

**Comment by stefan11** [comment]
I would never use the latter way since it is totally confusing. One should use \eal \ex \ex \zl instead.

**Comment by Glottotopia** [comment]
see https://github.com/langsci/25/issues/131

**Comment by kopeckyf** [comment]
I'd actually be mildly in favour of discontinuing **all** the lazy abbreviations, because

- There should be one, and only one, obvious way to do it (-> Zen of Python)
- They are undocumented
- They are buggy, as discussed here and in several other Github issues
- Their behaviour appears completely arbitrary by most users, especially new users
- Thus they make it harder to teach LaTeX to undergrad ling students

There are a number of other Zen of Python rules that these commands break ("Explicit is better than implicit", "Special cases aren't special enough to break the rules"). I just view them as pretty bad computer code.

**Comment by Glottotopia** [comment]
python is of course in favour of syntactic sugar. The "one and only one" refers to things like `stuff if condition` vs `if condition: stuff` vs `condition && stuff`. This is a reaction to TMTOWTDI in Perl. 

`\ea` is actually exactly the same way to do things as `\begin{exe}\ex` as far as the logic is concerned; it is just a shorthand. [arguably, there is a switch between `exe` and `xlist`, but this is actually akin to duck typing, which is not alien to python either]

Finally, the problematic behaviour noticed was in the definition of `exe` (the `\noraggedright`), not in the definition of one of the shorthands. 

This being said, I would only keep `\ea`, `\ex`, `\z` and probably `\zlast`.

**Comment by kopeckyf** [comment]
(I don't think that is an issue to be too worried about. At the end of the day, >99% of examples are typeset very fine.)

Sure, the analogy from python is quite a stretch but it is there. In Python, a user asks, "how can I enter the conditions for a loop", and Python says, do it this way, which is The One and Only Way.

In `langsci-gb4e`, the user asks, "How can I build an example", and `langsci-gb4e` says, well... here's >3 different ways of doing so, some of which are buggy, others that have an unintelligible `...l` at the end of their command name. Oh and forget about documentation. If you want to understand the difference between the commands, please could you read the source code, which is written in 1978 pure TeX style, in a file that is hidden somewhere in the TeX installation of your computer, or which is on CTAN in case you are using Overleaf.

**Comment by Glottotopia** [comment]
have you read the documentation at https://github.com/langsci/guidelines/blob/master/packages/langsci-gb4e/langsci-gb4.pdf? It seems you did not, since the documentation says very clearly how you should construct your examples.

**Comment by kopeckyf** [comment]
Documentation looks great! I hadn't seen this new version, only the one included in langsci/lsp-guidelines

In my rant I was thinking about `\eal`, `\eas`, `\eanoraggedright`.

**Comment by kopeckyf** [comment]
Idea: Add an optional argument `\ea[unskip]` that reverts the spacing added by a preceding `\z`. Maybe we'd also be able to automatically detect whether any text has been output between an `\z` and a new `\ea`, in which case we could have automatic spacing and `\ea[unskip=false]` in case one wanted to add the extra space (this happens sometimes). 

We could also have further optional arguments to `\ea` that would then replace the commands `\eal` or `\eas`.

**Comment by stefan11** [comment]
The "l" is for "list". \eal opens the list, \zl closes it. Fully transparent. Fully documented in the first langsci documents I wrote in 2013 or so. \eas is \ea plus some magic to keep things on the same page. If you do not like this, we could put it somewhere else. It is needed to keep a line of description and an AVM on the same page.

\begin{exe}\begin{xlist} is hardly iconic and frightens every latex rookie + me. I would never use something like this. It is way too technical and too much overhead to write a simple example. I want to tell people that latex is actually better than word since you just type in the example and the glossing is done automatically. If everybody has to remember cryptic stuff and type till their fingers fall off to get a simple example, this would not be good.

**Comment by stefan11** [comment]
Ah and I think Sebastian solved this problem by removing \nopagebreak somewhere in the definition of exe.

**Comment by kopeckyf** [comment]
I get the motivation of wanting to keep `\eal` and others for convenience, and of course they aren't going to stop working, at the very least because you can always include them in your personal `localcommands.sty`. It would probably be a good idea to make that command very local. Since everything we push to CTAN implies a constraint to everyone who uses our packages: You can't define `\eal` for something you'd need, although maybe you have no usage for the gb4e `\eal` at all.

What I don't get is the supposed advantage of `\eal`. The first issue is the name. I genuinely believed the `l` was for "left-aligned", because `\eal` also calls `\raggedright`. But even with the info that `l` is for "list", what sort of list should I be thinking of? List of examples? List of sub-examples? 

`\eal` is very opaque in the sense that it hides the actual structure that it creates. It will create sub-examples rather than examples, but the similarity of `\eal` to `\ea` suggests otherwise. I really don't know how I should be creating a header in the first line before the sub-examples with `\eal`, and is it even possible to include a `\label` in a `\eal` list so that it references not just one sub-example, but the complete structure?

I don't get what is wrong with:

```
\ea A good meal
  \ea Spam
  \ex Eggs
  \ex Bacon
  \ex More spam
  \z
\z
```

The fine thing about this is that, through indentation, the examples structure is quite clear. Also, I can append another example: 

```
\ea A good meal
  \ea Spam
  \ex Eggs
  \ex Bacon
  \ex More spam
  \z
\ex Christmas dinner
  \ea Lobster thermidor
  \ex aux crevettes
  \ex with mornay sauce
  \ex and spam
  \z  
\z
```

In an above comment, you called this lay out "totally confusing", and you said one "should" use the `\eal` approach. Frankly, I don't see how this judgement is warranted.

**Comment by stefan11** [comment]
\eal is from Detmar Meurer's package gb4e+, which I used and which was the basis of langsci-gb4e. A lot of people are using it. It is used in latex tutorials. Please leave it in. Thanks.

I cannot even think about \ea \ea. This only makes sense if you know what \ea does internally and people do not want to know this and do not want to think about it.

Yes, it is possible to have labels. I am using this package for 20 years now:
```latex
\eal
\label{ex-group}
\ex
\label{ex-foo}
foo
\ex
\label{ex-bar}
bar
\zl
```

Creating headers is not possible this way, one has to go to the manual and do whatever is described there. But this is a case that happens every 20 years. \eal and \zl are abbreviations and good ones.

**Comment by kopeckyf** [comment]
> I cannot even think about \ea \ea. This only makes sense if you know what \ea does internally and people do not want to know this and do not want to think about it.

It's so easy the explanation will fit on any _Bierdeckel_. `\ea` creates a list of examples. `\z` closes a list of examples. If `\ea` is called within an existing `\ea`, it creates a sub-list. `\z` will close only the current level of (sub-)list, so the number of `\ea` and `\z` in an example environment has to be identical.

Anyway, we're quite a long way from the original issue, which concerns the spacing between two `\ea...\z` environments. Maybe its best to return to that topic and have other discussions elsewhere.

**Comment by stefan11** [comment]
I think the original issue was long solved. Sebastian @Glottotopia  solved it by getting rid of the \nopagebreak, which cause this. It would be good if this \nopagebreak in the definitions of exe could be removed in the main class as well (if this was not done already).

**Comment by kopeckyf** [comment]
Unfortunately, the original issue is not solved. While it is true that the extra `\nopagebreak` amplifies the issue, the different spacing described in the OP still persits when no `\nopagebreak` are present.

**Comment by stefan11** [comment]
I have a file locallangscifixes.tex now. It contains some fixes, the one to gb4e among them:
```latex

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% gb4e

% fixes problem with to much vertical space between \zl and \eal due to the \nopagebreak
% command.
\makeatletter
\def\@exe[#1]{\ifnum \@xnumdepth >0%
                 \if@xrec\@exrecwarn\fi%
                 \if@noftnote\@exrecwarn\fi%
                 \@xnumdepth0\@listdepth0\@xrectrue%
                 \save@counters%
              \fi%
                 \advance\@xnumdepth \@ne \@@xsi%
                 \if@noftnote%
                        \begin{list}{(\thexnumi)}%
                        {\usecounter{xnumi}\@subex{#1}{\@gblabelsep}{0em}%
                        \setcounter{xnumi}{\value{equation}}}
% this is commented out here since it causes additional space between \zl and \eal 06.06.2020
%                        \nopagebreak}%
                 \else%
                        \begin{list}{(\roman{xnumi})}%
                        {\usecounter{xnumi}\@subex{(iiv)}{\@gblabelsep}{\footexindent}%
                        \setcounter{xnumi}{\value{fnx}}}%
                 \fi}
\makeatother

% the texlive 2020 langsci-gb4e adds a newline after \eas, the texlive 2017 version was OK.
\makeatletter
\def\eas{\ifnum\@xnumdepth=0\begin{exe}[(34)]\else\begin{xlist}[iv.]\fi\ex\begin{tabular}[t]{@{}b{.99\linewidth}@{}}}
\makeatother


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% biblatex

% biblatex sets the option autolang=hyphens
%
% This disables language shorthands. To avoid this, the hyphens code can be redefined
%
% https://tex.stackexchange.com/a/548047/18561

\makeatletter
\def\hyphenrules#1{%
  \edef\bbl@tempf{#1}%
  \bbl@fixname\bbl@tempf
  \bbl@iflanguage\bbl@tempf{%
    \expandafter\bbl@patterns\expandafter{\bbl@tempf}%
    \expandafter\ifx\csname\bbl@tempf hyphenmins\endcsname\relax
      \set@hyphenmins\tw@\thr@@\relax
    \else
      \expandafter\expandafter\expandafter\set@hyphenmins
      \csname\bbl@tempf hyphenmins\endcsname\relax
    \fi}}
\makeatother


% the package defined \attop in a way that produced a box that has textwidth
%
\def\attop#1{\leavevmode\begin{minipage}[t]{.995\linewidth}\strut\vskip-\baselineskip\begin{minipage}[t]{.995\linewidth}#1\end{minipage}\end{minipage}}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Don't do this at home. I do not like the smaller font for captions.
% This does not work. Throw out package caption in langscibook
% \captionsetup{%
% font={%
% stretch=1%.8%
% ,normalsize%,small%
% },%
% width=\textwidth%.8\textwidth
% }
% \setcaphanging
```
