### ISSUE TITLE
Remove inprep mode and old cover generation

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#107]
We currently have an `output=inprep` mode. As far as I can see, it is never used. It is also broken, since it uses the (now unsupported) old cover generation. The old cover generation uses the `textpos` package, the new one is `tikz`-based. 

I'm moving to:
- remove the `output=inprep` option
- unload the `textpos` package ([Line 679](https://github.com/langsci/langscibook/blob/34df4648ca3f88653733389d421716a49f0e3446/langsci/langscibook.cls#L679))
- remove the old cover generation method, which is build upon the `\begin{textblock}...\end{textblock}` bricks. ([Lines 847--](https://github.com/langsci/langscibook/blob/34df4648ca3f88653733389d421716a49f0e3446/langsci/langscibook.cls#L847))

Please approve these changes/comment if you'd like to keep (one of) these features.

**Comment by kopeckyf** [comment]
@timmli @Glottotopia what do you think?

**Comment by timmli** [comment]
OK with me. But it might be useful to have an output mode which is clearly marking that the book is a draft and not yet finished. Is `draftmode` used for this?

**Comment by kopeckyf** [comment]
> OK with me. But it might be useful to have an output mode which is clearly marking that the book is a draft and not yet finished. Is `draftmode` used for this?

Yes, `draftmode` will print a full-width water mark on the title page and a stamp on each footer saying "draft of (date)"

**Comment by timmli** [comment]
> > OK with me. But it might be useful to have an output mode which is clearly marking that the book is a draft and not yet finished. Is `draftmode` used for this?
> 
> Yes, `draftmode` will print a full-width water mark on the title page and a stamp on each footer saying "draft of (date)"

But appart from that it's not doing anything to the content, e.g. replacing figures with place holders?

**Comment by kopeckyf** [comment]
@timmli `draftmode` also adds markers for lines that overflow the margin. `draft` skips inclusion of external graphics.

**Comment by timmli** [comment]
If `draftmode` only changes some properties of the format (watermark, marking overlong lines), but not the the content, it's all good in my opinion.
