### ISSUE TITLE
series-info is empty and tbls is missing

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#112]

**Comment by Glottotopia** [comment]
works for me, and not enough context

**Comment by Glottotopia** [comment]
actually, doesn't work for me, so reopening

**Comment by stefan11** [comment]
OK. There is a directory seriesinfo. In this directory there are a lot of empty files. But the tbls file is missing. If this directory has a purpose, tbls-info.tex should be there.

**Comment by Glottotopia** [comment]
the directory seriesinfo can be deleted. You have to add the most recent `langsci-series.def` to your working directory

**Comment by stefan11** [comment]
Thanks. This all came up since langscibook.cls loads old langsci packages from somewhere elese in the texpath.
