### ISSUE TITLE
Italics in article titles -> Emphasis gets lost in headers

### ISSUE THREAD

**Issue by radeksimik** [langsci/langscibook#114]
If there's italics in an article title, as in \title{On \textit{li} in Macedonian}, the header is all in italics and there is no emphasis on _li_. Is there a way to make _li_ regular in headers?

**Comment by Glottotopia** [comment]
\title does not like markup. In the past, we have used
``` 
\title{\texorpdfstring{Word formation and word history:\\ The case of
 \textsc{capitalist} and \textsc{capitalism}}{Word formation and word
history:  CAPITALIST and
CAPITALISM}}

\renewcommand{\lsCollectionPaperFooterTitle}{Word formation and word
history: The case of  \noexpand\textsc{capitalist} and
\noexpand\textsc{capitalism}}
```

There is also a shorthand:
```
\markuptitle{A new theory of \textit{this} and \textit{that}}{A new theory of ``this'' and ``that''}
```

**Comment by Glottotopia** [comment]
Or you could try `\shorttitlerunninghead{On \textup{li} in Macedonian}`

**Comment by kopeckyf** [comment]
(Minor comment: I have been planning to look for a way to find a better integration of paper meta data to `scrbook` and this may be a good motivation to look for a new implementation of `\lsPaper`.)
