### ISSUE TITLE
@misc does not output the url field

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#116]
```
@misc{Nordhoff2018,
  author = {Sebastian Nordhoff},
  year = {2018},
  title = {BibTeX generator},
  url = {http://glottotopia.org/doc2tex/doc2bib},
  note = {Follow the link to generate BibTeX} 
}
```
becomes
`Nordhoff, Sebastian. 2018. Bibtex generator.` without the URL or the note

**Comment by Glottotopia** [comment]
seems to be true for `@book` as well @kopeckyf

**Comment by stefan11** [comment]
Yes, DOI and URL were commented out in some revision of the class. It has to be set to `true` again in the options of `biblatex`.

**Comment by kopeckyf** [comment]
Maybe #102 and https://github.com/langsci/langscibook/commit/2594fc9a0ee2c85c42674438d23ff2ca8e8f288a give a clue? In that commit, I unloaded the `doi` package and enabled the `biblatex` internal handling of DOIs. Could you verify that you are running with the appropriate `.bbx` and settings in the `.cls`?

**Comment by Glottotopia** [comment]
you can check this in the `tests/` directory with the current settings.

**Comment by kopeckyf** [comment]
Fixed in https://github.com/langsci/langscibook/commit/277607babfb2a9cc2cd2b17763c3ee11c4ed3ff2

Sorry, these were some remnants from the DOI package. 

It now prints fine:
![grafik](https://user-images.githubusercontent.com/10461729/81817044-67281080-952c-11ea-8748-bca47e2b0db9.png)

**Comment by kopeckyf** [comment]
As a side note: Our class currently prints both DOI and URL if both are present in a bib entry. Maybe the DOI should take priority if both are given. I don't know if there are any possible cases in which one wanted to have both.

**Comment by stefan11** [comment]
I think this is like \- without space. If the user wants this, there may be reasons. I rather have them remove the URL field.
