### ISSUE TITLE
Recent class does not load, loads langsci-linguex, which does not find ./lagsci-gb4e

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#118]
Log files from the HPSG book. I really have no clue who load langsci-linguex.sty. It is nowhere in my files and not in langsci files.

[main.log](https://github.com/langsci/langscibook/files/4623010/main.log)

**Comment by Glottotopia** [comment]
where do you load langsci-linguex?

**Comment by stefan11** [comment]
I do not load it. It happens mysteriously ...

**Comment by Glottotopia** [comment]
please paste a MNWE

**Comment by stefan11** [comment]
Kann ich das Buch einchecken und Ihr guckt dann? Zur Zeit kompiliert es auch keine Kapitel mehr. Da ist was ganz arg faul.

**Comment by stefan11** [comment]
Das ist im Branch flat langsci class.

Ich habe das Klassen-Update gemacht, weil bei mir auch das NOTE-Feld bei bibtex nicht rauskam.

**Comment by stefan11** [comment]
Die ganze Klasse lädt ohnehin nicht, wenn man nicht 
setenv TEXINPUTS ./langsci//:${TEXINPUTS}
macht. Dann lädt sie Dateien von texlive 2020.

**Comment by Glottotopia** [comment]
No MNWE, no support. Sorry.

**Comment by stefan11** [comment]
OK reverted to the previos state. You clean up the class. Will have a look in half a year ... =:-(

**Comment by kopeckyf** [comment]
The vanilla flat class from this directory does not load `linguex`, even when all the `.sty`s like `langsci-basic.sty` are included. Could you `grep -r linguex` your working directory?

**Comment by stefan11** [comment]
Ha, sorry! It is the main in langsci/tests/main.tex:\usepackage{langsci-linguex} which I compiled.
Due to my TEXINPUTS. 

With this TEXINPUTS it works. Almost.

setenv TEXINPUTS .:./styles//:$HOME/Library/texmf//:$HOME/Documents/Dienstlich/PS-Figures/:./langsci//:

\lsptoprule and \lspbottomrule 

are missing and \citegen and \largerpage as well.

I do not know why I have to say in the TEXPATH that subdirectories have to be looked at. Without this it does not find files like ccby.pdf, which are not there anyway. very mysterious.

The basic problem remains. Authors cannot use this on their systems, if langsci is installed somewhere in the main texpath.

Und um den Spaß zu erhöhen, hat Ash in das LFG-Kapitel ein \mainmatter eingefügt, so dass ich fast wahnsinnig wurde, weil ich dachte 90% des Buches sind weg. Es fing dann wieder neu an zu zählen, so dass der Seitenzähler am Ende bei 120 war ...
