### ISSUE TITLE
caption settings are incompatible with subfigure and floatrow

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#120]
The caption settings are incompatible with the subfigure and the floatrow style in which two figures are printed next to each other.

In the following example, the figure captions print on top of each other:

<img width="642" alt="grafik" src="https://user-images.githubusercontent.com/4655859/84594685-53860780-ae54-11ea-8aca-08732b1d2211.png">

```latex
%
\begin{figure}
\begin{floatrow}
\ffigbox{%
\begin{forest}
sm edges
[S
  [NP
  	[Ann,roof]]
  [INFL
  	[will]]
  [VP
  	[V$'$
		[V [read]]
		[NP[the newspaper, roof]]]]]
\end{forest}
}{\caption{\label{Abb-Old-School-Hilfsverb}Sentence with an auxiliary verb following
    \citet[\page 19]{Chomsky81a}}}
\ffigbox{%
\begin{forest}
sm edges
[IP
  [NP
  	[Ann,roof]]
  [I$'$
  	[I
  		[will]]
	[VP
  	[V$'$
		[V [read]]
		[NP[the newspaper, roof]]]]]]
\end{forest}}
{\caption{\label{Abb-GB-Hilfsverb}Sentence with auxiliary verb in the CP/IP system}}
\end{floatrow}
\end{figure}%
```
In the following example the subcations are shifted rightwards:

<img width="612" alt="grafik" src="https://user-images.githubusercontent.com/4655859/84594738-9e078400-ae54-11ea-9815-c750bf0c7fd1.png">

\begin{figure}[htb]
\hfill\subfloat[Trace]{%
\hspace{1cm} % adding some space here for the subcaptions
\begin{forest}
  [V$'$
    [V [read]]
    [\trace$_i$]]
\end{forest}
\hspace{1cm}\label{fig-traces-trace}}
\hfill
\subfloat[XP with empty daughter]{
\hspace{1cm}
\begin{forest}
  [V$'$
    [V [read]]
    [NP[\trace$_i$]]]
\end{forest}
\hspace{1cm}\label{fig-traces-xp}}
\hfill
\subfloat[Mix of a and b]{
\hspace{1cm}\begin{forest}
  [V$'$
    [V [read]]
    [NP$_i$ [\trace]]]
\end{forest}\hspace{1cm}\label{fig-traces-mix}}
\hfill\mbox{}
\caption{Alternative ways of depicting movement: the moved constituent can be represented by a trace
or by an XP dominating a trace}\label{fig-traces}
\end{figure}

It would be great if loading the caption package and specifying the settings could be made optional or dependent on the series.

Examples from English GT book chapter 3-gb.tex.

**Comment by kopeckyf** [comment]
Please use the `subcaption` package. The `subcaption` package is distributed along with `caption` and is loaded via `\usepackage{subcaption}`. So this is kind of the natural way to make subfloats in a place where the `caption` pkg is loaded.

One other benefit of `subcaption` besides compatibility with `caption` is a better syntax.

![Screenshot_20200615_082013](https://user-images.githubusercontent.com/10461729/84624274-5a0e9080-aee1-11ea-8d54-89c0a4063a24.png)

```
\begin{figure}
	\caption{Please provide a caption}
	\begin{subfigure}[b]{.45\linewidth}
			\begin{forest}
				[S
				[NP
				[Ann,roof]]
				[INFL
				[will]]
				[VP
				[V$'$
				[V [read]]
				[NP[the newspaper, roof]]]]]
			\end{forest}
		\caption{\label{Abb-Old-School-Hilfsverb}Sentence with an auxiliary verb following
\citet[19]{Chomsky81a}}
\end{subfigure}\hfill\begin{subfigure}[b]{.45\linewidth}
			\begin{forest}
				[IP
				[NP
				[Ann,roof]]
				[I$'$
				[I
				[will]]
				[VP
				[V$'$
				[V [read]]
				[NP[the newspaper, roof]]]]]]
		\end{forest}
		\caption{\label{Abb-GB-Hilfsverb}Sentence with auxiliary verb in the CP/IP system}
		\end{subfigure}
\end{figure}
```

**Comment by kopeckyf** [comment]
And for your other example below. As you can see, the `subfigure` environment needs an extra call to `\centering` in some scenarios. I hope that's not too much of an inconvenience.

```
\begin{figure}\hfill%
	\begin{subfigure}[b]{.3\textwidth}\centering
		\begin{forest}
			[V$'$
[V [read]]
[blub$_i$]]
		\end{forest}
			\caption{Trace\label{fig-traces-trace}}
	\end{subfigure}\hfill
%
	\begin{subfigure}[b]{.3\textwidth}\centering
		\begin{forest}
			[V$'$
[V [read]]
[NP[bla$_i$]]]
		\end{forest}
		\caption{XP with empty daughter}
	\end{subfigure}\hfill%
	\begin{subfigure}[b]{.3\textwidth}\centering
		\begin{forest}
			[V$'$
[V [read]]
[NP$_i$ [bla]]]
		\end{forest}
		\caption{Mix of a and b\label{fig-traces-mix}}
		\end{subfigure}\hfill
	\caption{Alternative ways of depicting movement: the moved constituent can be represented by a trace
or by an XP dominating a trace}\label{fig-traces}
\end{figure}
```

**Comment by kopeckyf** [comment]
Additionally, using `floatrow` in a document with a specific `caption` setup is possible with `\captionsetup`. Within this command, one can locally adjust previously made settings. I'd suggest something like

```
\begin{floatrow}
  \captionsetup{margin=.05\linewidth}
  ...
\end{floatrow}
```

**Comment by kopeckyf** [comment]
The solutions to this issue are now included our guidelines via https://github.com/langsci/guidelines/commit/6f260306a9245f2440a826f0831279b40aa80b7c.
