### ISSUE TITLE
judgements in translations of numbered examples

### ISSUE THREAD

**Issue by jonorthwash** [langsci/langscibook#127]
I see in the `langsci-gb4e` documentation that judgements can be added to examples with brackets, e.g. `\ex[*]`.

However, I have an example where I need to add a judgement to the gloss.  This is possible with `expex`, but I can't figure out how to do it with `langsci-gb4e`.

An example of what I'm after:
```
(1) an example
  kɘtɑpχɑnɑʁɑ  bɑɾʁɑndɑɾdə
  kɘtɑpχɑnɑ-GA bar-GAn-LAr-NI
  library-DAT go-VADJ-PL-ACC
* ‘goings to the library’
  ‘[the ones] who go to the library’
```

How can I do this with `langsci-gb4e`?

**Comment by kopeckyf** [comment]
Solution 1: You can safely use `expex` with `langscibook`. I'd encourage you to use `expex` with `langscibook` if you are confident with `expex` but not with `gb4e`.

Solution 2: Manually align spacing with `\hphantom`:

```latex
\documentclass[varwidth]{standalone}
\usepackage{langsci-gb4e}
\begin{document}
	\begin{exe}
		\ex an example\\
		 \hphantom{*} \glll kɘtɑpχɑnɑʁɑ  bɑɾʁɑndɑɾdə\\
		kɘtɑpχɑnɑ-GA bar-GAn-LAr-NI\\
		library-DAT go-VADJ-PL-ACC\\
		\glt * ‘goings to the library’
		\glt \hphantom{*} ‘[the ones] who go to the library’
	\end{exe}
\end{document}
```
