### ISSUE TITLE
Float labels should not include chapter number in edited volumes

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#141]
The inclusion of the chapter is not necessary. In the HPSG handbook there is only one crosschapter reference to another figure. It would be good if the chapter would be removed again.

**Comment by kopeckyf** [comment]
Besides floats, I will change this for equations as well, s.t. equations are counted per chapter, but the chapter number is not part of the label.

If one adds new types of floats (e.g. "Map"), computer code listings, etc., one must be careful to make the same adjustments for that particular object.

**Comment by Glottotopia** [comment]
this is still being discussed, so please do not change anything for the
moment
