### ISSUE TITLE
langsci-affiliations.sty missing

### ISSUE THREAD

**Issue by timmli** [langsci/langscibook#142]
In the latest stable release, [2020-2.0](https://github.com/langsci/langscibook/releases/tag/2020-2.0), the file `langsci-affiliations.sty` is missing which is now used in the class:

```latex
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%    Early load packages
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\RequirePackage[]{silence}
\WarningsOff[hyperref]
\WarningsOff[microtype]
\WarningFilter{microtype}{Unknown slot}
\WarningFilter{scrbook}{package incompatibility}
\WarningFilter{todonotes}{The length}
\WarningFilter{biblatex}{'babel/polyglossia'}
\hbadness=99999 % get rid of underfull box warnings
\typeout{Warnings are disabled in langscibook.cls for underfull boxes, hyperref, microtype and scrbook package incompatibility, todonotes length and babel/polyglossia csquotes}
\usepackage{etoolbox}
\RequirePackage{xparse}
\usepackage{langsci-affiliations}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%     Default values
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
This will obviously cause an error during compilation.

**Comment by kopeckyf** [comment]
Thanks for mentioning that - the release v2020-2.0 is designed to run on an up to date TeX Live 2020 installation synchronised with CTAN. In these, `langsci-affiliations` should be included. If not, you can obtain a `.sty` file from here: https://github.com/langsci/langsci-affiliations/releases/tag/v1.0.3

**Comment by timmli** [comment]
I see. But I would recommend to mention this as a requirement or even better add langsci-affiliation as a submodule, since this is not a standard package. Thanks!

**Comment by kopeckyf** [comment]
Mh, we are always in a pickle when it comes to requiring up-to-date versions of other packages. `langsci-affiliations` stands out a little because we are also the distributor of that package, but in principle this can happen to any package out there, and it has happened particularly with `scrbook` and `biblatex`.

In the future I will make it more clear in the release notes of each release which version of TeX Live and which CTAN state is required to run a version of langscibook.

**Comment by Glottotopia** [comment]
Note that `langsci-affiliations.sty` is  integrated into the main `langsci` package as of TL2021 in order to avoid precisely this situation.

**Comment by kopeckyf** [comment]
@timmli in the release notes for 2020-2.0, I inserted a line 
```This release requires TeX Live 2020 and synchronised CTAN packages not older than 1 April 2021.```
to make the requirements more clear.

**Comment by kopeckyf** [comment]
> Note that `langsci-affiliations.sty` is integrated into the main `langsci` package as of TL2021 in order to avoid precisely this situation.

This is not the same situation, OP here seems to have used a GitHub version of `langscibook`, which we usually discourage anyway, though of course there may be good reasons to do so.

**Comment by timmli** [comment]
> > Note that `langsci-affiliations.sty` is integrated into the main `langsci` package as of TL2021 in order to avoid precisely this situation.
> 
> This is not the same situation, OP here seems to have used a GitHub version of `langscibook`, which we usually discourage anyway, though of course there may be good reasons to do so.

Yep, I'm using the Github version out of a maybe bad habit ;-) And I have TeXLive 2019 running.
