### ISSUE TITLE
Undefined commands in langsci-textipa

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#143]
When `langsci-textipa.sty` is loaded in a minimal `langscibook` document, these commands are reported as undefined:

```latex
l.48 \renewcommand{\textepsilon}
                                {ɛ}
l.55 \renewcommand{\textgamma}
                              {ɣ}
l.115 \renewcommand{\textrho}
                             {ρ}
l.155 \renewcommand{\textsigma}
                               {}
```

This also happens in some live book projects. It looks a bit odd that `\textsigma` has an empty definition.

**Comment by Glottotopia** [comment]
the `\text...` provided by a TL installation seem to change between installations. Which installation are you reporting on? As a result, some `\renewcommand{}`s complain. 

As for `\textsigma`, it is true that `{}` is wrong. The question is which of the two sigmas should be the standard one.

**Comment by kopeckyf** [comment]
I'm seeing this on TeX Live 2020, XeLaTeX version 3.14159265-2.6-0.999992

**Comment by Glottotopia** [comment]
On my computer, the following document does not produce any error:
```
\documentclass{langscibook}
\usepackage{langsci-textipa}
\begin{document}
a
\end{document}
```
[XeTeX 3.14159265-2.6-0.999992]

**Comment by kopeckyf** [comment]
Did you try it in [`tests/book-main.tex`](https://github.com/langsci/langscibook/blob/master/tests/book-main.tex)? That's where I see the error (among other places)

**Comment by Glottotopia** [comment]
again, can't reproduce. Maybe you have an old copy of `langsci-lgr.sty` in your working directory?

**Comment by kopeckyf** [comment]
General comment: In the future, we could see whether the recently released package [`tipauni`](https://ctan.org/pkg/tipauni) provides a better solution for TIPA typesetting. `tipauni` is a parser on TIPA input that produces Unicode glyphs instead of the T3 font encoding.

**Comment by kopeckyf** [comment]
@Glottotopia, the following minimal document fails on Overleaf for TeX Live 2022, 2023, and 2024:

```latex
\documentclass{langscibook}
\usepackage{langsci-textipa}

\begin{document}
Hello World
\end{document}
```

I wonder whether `\providecommand` (creates a new definition only if one has not already been given) should be used instead.
