### ISSUE TITLE
Chinese translations for 2 fields in langscibook.cls: 1 correction and 1 addition

### ISSUE THREAD

**Issue by alexis-michaud** [langsci/langscibook#153]
This is to suggest 1 modification and 1 addition to Chinese translations of fields in langscibook.cls, here (lines 2210-2216):

```
\ifx\lsBookLanguage\lsBookLanguageChinese
    \renewcommand{\lsIndexTitle}{索引}
    \renewcommand{\lsNameIndexTitle}{人名索引}
    \renewcommand{\lsSubjectIndexTitle}{术语索引}
    \renewcommand{\lsLanguageIndexTitle}{语言索引}
    \renewcommand{\lsPrefaceTitle}{前言}
    \renewcommand{\lsAcknowledgementTitle}{致谢}
    \renewcommand{\lsAbbreviationsTitle}{\colorbox{red}{Translation info for Abbv missing}}
\fi
```

(i) For Preface title: 前言 is not quite right, it means **Introduction** not Preface. Preface is: 序言
`    \renewcommand{\lsPrefaceTitle}{序言}`
(ii) For abbreviations (which was missing so far): 缩写
`    \renewcommand{\lsAbbreviationsTitle}{缩写}`

Hence:
```
\ifx\lsBookLanguage\lsBookLanguageChinese
    \renewcommand{\lsIndexTitle}{索引}
    \renewcommand{\lsNameIndexTitle}{人名索引}
    \renewcommand{\lsSubjectIndexTitle}{术语索引}
    \renewcommand{\lsLanguageIndexTitle}{语言索引}
    \renewcommand{\lsPrefaceTitle}{序言}
    \renewcommand{\lsAcknowledgementTitle}{致谢}
    \renewcommand{\lsAbbreviationsTitle}{缩写}
\fi
```

_Voilà !_ Just a change of 3 Chinese characters in total :)

It will break backwards compatibility for [177](https://github.com/langsci/177/), where the introductory materials are labelled "Preface" but translated as "Introduction". I guess it's OK, since the code for 177 will continue to live in its own repo?

**Comment by kopeckyf** [comment]
Thanks Alexis! Are you sure about 前言 and 序言 though?

**Comment by alexis-michaud** [comment]
Good point! I was rather hasty in proposing this. On closer verification, 前言 is OK as a translation for Preface (as done for book 177).

Uses in different languages do not match exactly.

_Introduction_ can be a very short piece (introductory words) or a longer one (presenting the state of the art, elaborating a research question and how it is to be addressed). The term 'introduction' is best translated as **前言** if it is a substantial piece of writing (by the book's author(s)). If it is short, it is oftentimes referred to as **引言** (or 导言 or 导论).

_Preface_ can also correspond to different genres (less tightly linked to the main text than an Introduction): 
* if written by the author: 序言 or 前言 (in case there is both a Preface and an Introduction, the Preface will be 序言 and the Introduction will be 前言)  
* if written by someone else: 序言 [=same term as for 'Foreword']

_Foreword_ :: 序言 [=same term as for 'Preface']

Does this help? I can ask the input of native speakers of Chinese with editorial experience if useful.

**Comment by kopeckyf** [comment]
Thank you Alexis, this is very instructive. Given the variety of use cases I propose that we do not change the translation for _Preface_ and _Introduction_ but leave it to individual authors, editors and/or translators to decide given their particular case.

I have already added the missing translation for _Abbreviations_ (in https://github.com/langsci/langscibook/commit/1a0b637fc4afd0b2cce6c322d0a3f695e1ed11e1). Many thanks for helping improve langscibook!
