### ISSUE TITLE
replace index by imakeidx

### ISSUE THREAD

**Issue by timmli** [langsci/langscibook#23]

**Comment by Glottotopia** [comment]
can this be closed?

**Comment by timmli** [comment]
not sure yet

**Comment by Glottotopia** [comment]
any new insights?

**Comment by timmli** [comment]
If you're happy with the status quo, this can be closed.

**Comment by kopeckyf** [comment]
We will need to switch to another index package for the TeX Live 2020 migration. Since `imakeidx` is maintained by the prolific TeXpert Enrico Gregorio, I think `imakeidx` is our best shot in the long run. I'd also hope we could gain Unicode support.
