### ISSUE TITLE
ISBN barcode and text overlap on back page

### ISSUE THREAD

**Issue by timmli** [langsci/langscibook#36]

**Comment by kopeckyf** [comment]
@timmli is this the same problem you mentioned in your comment to #84 ?

**Comment by timmli** [comment]
No, #84 is a different one, which probably does not exist anymore. #36 is concerned with the text of the back cover that is supposed to float around the barcode.

**Comment by Glottotopia** [comment]
text on the back should probably not be allowed to be as long as to reach the bar code in the first place
