### ISSUE TITLE
Replace Libertine with Libertinus?

### ISSUE THREAD

**Issue by timmli** [langsci/langscibook#62]

**Comment by Glottotopia** [comment]
any news in the last year about this?

**Comment by timmli** [comment]
Some issues of Libertinus have to be fixed first IMHO, e.g. the size of math operators: https://github.com/libertinus-fonts/libertinus/issues/63

**Comment by timmli** [comment]
In the meanwhile, the issue with the size of math operators seems to have been fixed: https://github.com/alif-type/libertinus/pull/272

If there's no dissent, I can do the replacement.

**Comment by kopeckyf** [comment]
I've switched to Libertinus today - we now have the capability of actively contributing to the further development of Libertinus via the langsci/langsci-libertinus repository. The maintainer of alif-type/libertinus is happy to accept pull requests for missing symbols.

I also added XITS today to our document class which is a font that has additional math glyph support - it was needed in two recent projects.
