### ISSUE TITLE
Title in footer citation must not include font macros such as \emph

### ISSUE THREAD

**Issue by timmli** [langsci/langscibook#68]
The footer citation of collection papers is generated with BibLaTeX by processing an bib entry that has been written to a temporary file with `\immediate\write\tempfile`. There, a problem may occur with an too early expansion of macros such as `\emph`, which causes BibLaTeX to crash. This can be prevented by explicitely prohibiting expansion with `\noexpand`.
```
\title{This is \emph{emphasized}}
\renewcommand{\lsCollectionPaperFooterTitle}{This is \noexpand\emph{emphasized}}
```

There should be a more general solution that spares one to manually put `\noexpand` in front of every macro.

This issue has first been raised here: https://github.com/langsci/hoehle/issues/104

**Comment by Glottotopia** [comment]
The current setup causes the error "could not read file collection_tmp", leading biber to abort, leading to compilation failure on Overleaf @timmli

**Comment by Glottotopia** [comment]
There is now a command `\markuptitle{with markup}{without markup}` where two strings can be provided. One or the other will be used depending on the requirements of the context (title on page, toc, footer, page header)
