### ISSUE TITLE
Offering developer documentation for langsci-gb4e ?

### ISSUE THREAD

**Issue by alexis-michaud** [langsci/langscibook#74]
LaTeX aesthete and LangSciPress supporter number 635 Thomas Pellard notes, in [a blog post about glossed examples in LaTeX](https://cipanglo.hypotheses.org/349): 
"La version modifiée de gb4e proposée par Language Science Press semble proposer des ajustements intéressants, mais il n’y a malheureusement pas de documentation sur les modifications apportées."

Wouldn't it be cool for greater reusability if the changes made for langsci-gb4e.sty were documented, through comments inside the file and/or a documentation file?

**Comment by Glottotopia** [comment]
I am preparing some documentation. You can have a look at the current version here. Comments welcome 
[langsci-gb4.pdf](https://github.com/langsci/langscibook/files/3901590/langsci-gb4.pdf)
@tpellard

**Comment by Glottotopia** [comment]
https://github.com/langsci/guidelines/blob/master/packages/langsci-gb4e/langsci-gb4.tex

**Comment by tpellard** [comment]
You might be interested in my own package for simplifying the formatting of glosses under gb4e: https://github.com/tpellard/typgloss

**Comment by Glottotopia** [comment]
OK, thanks for the info. We will give it a try. 
Have you considered uploading the package to CTAN? https://ctan.org/upload 
This will make sure that there is an authoritative version (unlike `avm.sty`, of which there exist 12 different versions in the wild, and you can never be sure who used which).

**Comment by tpellard** [comment]
I'm waiting for some feedback before uploading it to CTAN.

**Comment by Glottotopia** [comment]
documentation now available at https://github.com/langsci/guidelines/blob/master/packages/langsci-gb4e/langsci-gb4.pdf
