### ISSUE TITLE
German shorthands for hyphenation "" do not work with biblatex due to ordering paradox

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#76]
The stuff is described here:

https://github.com/langsci/hoehle/issues/222

I guess we are supposed to use babel rather than german. If so it would be great if the shorthands could be activated before biblatex.

**Comment by timmli** [comment]
As an option, right?

**Comment by stefan11** [comment]
Yes, I guess this would be the right thing to do since it may interfere with a hell of other things.

**Comment by timmli** [comment]
See commit 3766adcd95a8a36d30dd7deac17fd5c1e357b57c.

**Comment by stefan11** [comment]
There may be a problem for users of `ngerman`, who do not want `german`.

**Comment by stefan11** [comment]
It does not work. Is the package loaded in the right order with biblatex?  
![bildschirmfoto 2018-01-15 um 06 32 16](https://user-images.githubusercontent.com/4655859/34928457-ea404b52-f9bd-11e7-98a3-9096fc72435c.png)

https://tex.stackexchange.com/questions/410021/german-quote-shorthands-from-babel-for-biblatex/410023#410023

**Comment by timmli** [comment]
Yes. I have overlooked "biblatex" somehow. Do you think it's dangerous to put `babel` settings  ("Language-specific settings") before `biblatex`?

**Comment by stefan11** [comment]
@timmli It was just a paradox for me outside the class but inside the class you can do it the way it has to be. Thanks.

**Comment by Glottotopia** [comment]
is this solved @stefan11 ?

**Comment by stefan11** [comment]
I guess so.
