### ISSUE TITLE
No colon before subtitle when title ends in ?

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#79]
The current class produces the following as citation text on page ii
```
Wendy Fox. 2018. Can integrated titles improve the viewing experience?:
Investigating the impact of subtitling on the reception and enjoyment of film using
eye tracking and questionnaire data (Translation and Multilingual Natural
Language Processing 9). Berlin: Language Science Press.
```
The `?:` should only be `?`.

**Comment by timmli** [comment]
The problem is, that the citation text is not generated by BibLaTeX, but with this macro:

````latex
\newcommand{\lsImpressumCitationText}{
  \onlyAuthor
  \renewcommand{\newlineCover}{}
  \renewcommand{\newlineSpine}{}
  {\@author}\if\lsEditorSuffix\empty\else\ \lsEditorSuffix\fi. %
  {\lsYear}. %
  \textit{\@title}\if\@subtitle\empty\else: \textit{\@subtitle}\fi\ %
  (\lsSeriesTitle). %
  Berlin: Language Science Press.
}
````
As a workaround you could redefine it manually:

```latex
\newcommand{\lsImpressumCitationText}{%
Wendy Fox. 2018. Can integrated titles improve the viewing experience? Investigating the impact of subtitling on the reception and enjoyment of film using eye tracking and questionnaire data (Translation and Multilingual Natural Language Processing 9). Berlin: Language Science Press.%
}
```

Please keep this issue open. I need to check whether there is a way to use BibLaTeX like in the footers of collection contributions.

**Comment by kopeckyf** [comment]
So I replaced the citation information on the imprint page, only to discover that biblatex, by default, does **not** recognise the question mark in `\addcolon` - however, it does recognise other punctuation marks. I hope to hear back from the package author on this topic soon.
