### ISSUE TITLE
\Citet does not capitalize

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#81]
\\citet{vanTrijp} should come out as Van Trijp even though the name in the BibTeX item is "van Trijp"

https://github.com/langsci/25/issues/41

**Comment by haspelmath** [comment]
Yes, in Dutch texts, but not in English texts (unless van Trijp occurs sentence-initially).

**Comment by stefan11** [comment]
Martin, es geht um ein Kommando, nicht um die Verwendung des Kommandos. Wenn ich \\Citet statt \\citet schreibe, dann soll es groß sein und das ist es gerade nicht. Im konkreten Fall https://github.com/langsci/25/issues/41 geht es um den Satzanfang.

**Comment by kopeckyf** [comment]
This was fixed by inserting `useprefix=true` [in langscibook.cls](https://github.com/langsci/langscibook/blob/e2f7e5c019d97b6b7d7fec67de8223de76545237/langsci/langscibook.cls#L1454)
