### ISSUE TITLE
ISBN barcode not working with TexLive2017

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#84]
there is only a blank rectangle. It does work with TexLive2016

**Comment by timmli** [comment]
When I use `make test_book` under TeX Live 2018, the barcode is printed, though with a slim black rectangle on the right:

![unbenannt](https://user-images.githubusercontent.com/4593031/38501931-6d1e1a44-3c0e-11e8-8ac6-f6a23c93fad7.PNG)

**Comment by Glottotopia** [comment]
We are Texlive 2020 now
