### ISSUE TITLE
\KOMAoptions{footnotes=multiple} has to be set before laoding hyperref package

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#85]
Komascript overloads what hyperref does. The effect is that footnotes are not linked and hyperref complains with warnings. I fixed this locally but did not dare to do this in the main class since it may have side effects.

https://github.com/langsci/177/issues/151

**Comment by kopeckyf** [comment]
This issue was solved in Version 2020-1.0. See the changelog there for details. Footnotes are no longer hyperlinked in `langscibook` because of limitations of the feature in `hyperref`.
