### ISSUE TITLE
Examples in footnotes have normal font size

### ISSUE THREAD

**Issue by kopeckyf** [langsci/langscibook#88]
For example in,

`\lipsum\footnote{\ea Test \z}`

The example "Test" will not be printed in \footnotesize, although there are instructions in langsci-gb4e.sty to do so.

**Comment by stefan11** [comment]
I fixed this in the HPSG-Handbook. It depends on the order of package loadings since the footnote commands are redefined.

**Comment by kopeckyf** [comment]
Thank you! I adjusted the load order in localpackages.tex [(57b71d6)](https://github.com/langsci/latex-skeletons/commit/57b71d6a7bf5f09974338b0b90cce3353863c555)
