### ISSUE TITLE
"Missing number, treated as zero" with multiple entries with identical authors and years

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#92]
The current bibliography setup occasionally causes `Missing number` errors when small lettes `abc` are used for disambiguation, like "(Smith2000a,b,c)". 

This problem surfaces when : 
- there are two or more entries in a `\citet` command (also `\cite`, `\citealt`, `\citep`)
- at least of the entries requires disambiguations with `abc`, and at least one other doesn't
- an entry requiring disambiguation precedes an entry not requiring disambiguation

So: 
- Smith (2000) is fine
- Smith (2000a,b) is fine
- Smith (2000; 2001a,b) is fine
- Smith (1999a; 2000) breaks
- Smith (1999a,b; 2000) breaks
- Smith (1999a; 2001b) works
- Smith (1999a,b; 2001a) works

This is on TexLive2017 on my local machine. Bizarrely enough, on Overleaf, the problem does not surface: https://v2.overleaf.com/read/hgmjmmtcpxtn 

[bibmissingnouns.tex.txt](https://github.com/langsci/langscibook/files/2404797/bibmissingnouns.tex.txt)
![bibmissingnumber](https://user-images.githubusercontent.com/1553576/45874288-bee09980-bd94-11e8-8354-dee56d8c36fb.png)

**Comment by stefan11** [comment]
Cool. Does this mean that we are ready for texlive 2018?
