### ISSUE TITLE
integrate bibstyle modifications into bbx

### ISSUE THREAD

**Issue by Glottotopia** [langsci/langscibook#95]
langscibook.cls currently contains the following code

```
\renewcommand{\postnotedelim}{: }%
\DeclareFieldFormat{postnote}{#1}% display pages without page prefix (p., pp.)
```

That code, and similar lines, should be moved to the relevant bibstyles so that the modifications are available outside of langscibook.cls as well

**Comment by Glottotopia** [comment]
is this done @kopeckyf ? Then you could close this issue

**Comment by kopeckyf** [comment]
`\postnotedelim` is part of our `cbx`:
https://github.com/langsci/langscibook/blob/a71e3657b1c392e8e0ce0b99c11552a2c10d4645/langsci-unified.cbx#L395

and the postnote field format is in the `bbx`:
https://github.com/langsci/langscibook/blob/a71e3657b1c392e8e0ce0b99c11552a2c10d4645/langsci-unified.bbx#L728
