### ISSUE TITLE
\glt adds strange space

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#97]
In the HPSG handbook we had two different examples:

```latex
\eal \label{gram}
\ex 
\gll Fred ging-e       ins    Kino.\\ 
     Fred went-\SBJV{} to.the movies\\  \hfill (Present-day German)
%\glt `Fred would go to the movies.'
\ex
\gll Fred würde ins Kino gehen.\\ 
     Fred \SBJV{} to.the movies go\\  \hfill (Present-day German)
\glt `Fred would go to the movies.'
\zl
```
The call of \glt causes some extra space to the right of the language statement:

<img width="497" alt="bildschirmfoto 2019-02-01 um 20 29 50" src="https://user-images.githubusercontent.com/4655859/52145193-a3e63600-2660-11e9-8133-637bef383e74.png">
<img width="500" alt="bildschirmfoto 2019-02-01 um 20 27 40" src="https://user-images.githubusercontent.com/4655859/52145195-a3e63600-2660-11e9-8262-4300250a4c6b.png">

In the second example the space is added to both language expressions, so they seem OK.

**Comment by Glottotopia** [comment]
does this persist if you use `jambox` instead? 

Probably, `\glt` does something to the line before calling the newline. This something is then appended after the final `)`, so that the `)` does not float completely to the right margin.
