### ISSUE TITLE
langsci-gb4 should load ./langsci/styles/...cgloss

### ISSUE THREAD

**Issue by stefan11** [langsci/langscibook#99]
tex complained about not finding cgloss. It works in other systems since cgloss is probably loaded from the main tex distribution.

**Comment by Glottotopia** [comment]
langsci-gb4e loads langsci-cgloss, which is on CTAN. In any case, please give a more detailed description of which package is not found, and which other package or file requires the missing package.

**Comment by stefan11** [comment]
> In any case, please give a more detailed description of which package is not found, and which other package or file requires the missing package.

This was in the header. langsci-gb4e tries to load langsci-cgloss. This fails since it does not find the file in the path. If you installed the package in texlive, it may work, but it did not work on Ulrike Demske's computer (ubuntu) and I guess it will not work on many other computers.
